modLoader = "javafml"
loaderVersion = "[2,)"
license = "GNU General Public License, v3.0"
issueTrackerURL = "https://github.com/PolyhedralDev/Terra/issues"

[[mods]]
modId = "terra"
version = "@VERSION@"
displayName = "Terra"
credits = "Includes modified code from Origen by Rearth (https://github.com/Rearth/Origen), licensed under CC-BY-4.0."
description = "@DESCRIPTION@"

[[dependencies.terra]]
modId = "neoforge"
mandatory = true
versionRange = "[21.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.terra]]
modId = "minecraft"
mandatory = true
versionRange = "[1.21.1,)"
ordering = "NONE"
side = "BOTH"

[[mixins]]
config = "terra.neoforge.mixins.json"
